[Properties]

[Properties.feature]
subtasks = ["(feature) validation by programmer", "(feature) implementation"]

[Properties.feat]

[Properties.bug]

[Properties.foo]
subtasks = ["bar", "baz"]
subtasks_allow_cancel = [false, true]

[Properties.feature2]
subtasks = ["1. dev implementation", "2. dev documentation", "3. test", "4. developer #review"]

[Users]

[Users.alice]

[Users.smassa]
git_names = ["Simon Massa", "smassa", "massmde", "masssmde"]
git_emails = ["simon.massa@hotmail.de"]


[Groups]

[Groups.devs]
members = ["alice"]

[Groups.QM]
members = ["smassa"]
[Properties.review]
