[Properties.feature]
subtasks = ["(feature) validation by programmer", "(feature) implementation"]

[Properties.bug]
[Properties.foo]
subtasks = ["bar", "baz"]

[Properties.feat]

[Users.alice]

[Group.devs]
